name: Publish to GitHub Pages

on:
  workflow_dispatch: # 手動で動かすための「Run workflow」ボタンを出します

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # scratch-guiが安定して動くバージョン
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Web Version
        # ★ここで、先ほどのmicro:bitの暗号化エラーを強制的に回避させます
        run: npm run build
        env:
          NODE_ENV: production
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Upload Website Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
